# Generated by Django 5.2.3 on 2025-06-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Course_title", models.CharField(max_length=200)),
                ("Course_description", models.TextField()),
                ("Course_start_date", models.DateField()),
                ("Course_end_date", models.DateField()),
                ("Course_instructor", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Course",
                "ordering": ["Course_title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_name", models.CharField(max_length=200)),
                ("lesson_content", models.TextField()),
                ("lesson_order", models.PositiveIntegerField()),
                ("slug", models.SlugField(max_length=200)),
                (
                    "lesson_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lesson",
                "ordering": ["lesson_order"],
                "unique_together": {("lesson_name", "lesson_course")},
            },
        ),
    ]
