# Generated by Django 5.2 on 2025-06-20 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["Course_title"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["lesson_order"],
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="Course_description_de",
            field=models.TextField(null=True, verbose_name="Course Description"),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_description_en",
            field=models.TextField(null=True, verbose_name="Course Description"),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_description_es",
            field=models.TextField(null=True, verbose_name="Course Description"),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_description_fa",
            field=models.TextField(null=True, verbose_name="Course Description"),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_description_fr",
            field=models.TextField(null=True, verbose_name="Course Description"),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_description_it",
            field=models.TextField(null=True, verbose_name="Course Description"),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_instructor_de",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Course Instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_instructor_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Course Instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_instructor_es",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Course Instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_instructor_fa",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Course Instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_instructor_fr",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Course Instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_instructor_it",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Course Instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_title_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Course Title"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Course Title"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_title_es",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Course Title"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_title_fa",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Course Title"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_title_fr",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Course Title"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Course_title_it",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Course Title"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_content_de",
            field=models.TextField(null=True, verbose_name="Lesson Content"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_content_en",
            field=models.TextField(null=True, verbose_name="Lesson Content"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_content_es",
            field=models.TextField(null=True, verbose_name="Lesson Content"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_content_fa",
            field=models.TextField(null=True, verbose_name="Lesson Content"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_content_fr",
            field=models.TextField(null=True, verbose_name="Lesson Content"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_content_it",
            field=models.TextField(null=True, verbose_name="Lesson Content"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_name_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Lesson Name"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Lesson Name"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_name_es",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Lesson Name"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_name_fa",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Lesson Name"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_name_fr",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Lesson Name"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_name_it",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Lesson Name"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="Course_description",
            field=models.TextField(verbose_name="Course Description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="Course_end_date",
            field=models.DateField(verbose_name="Course End Date"),
        ),
        migrations.AlterField(
            model_name="course",
            name="Course_instructor",
            field=models.CharField(max_length=100, verbose_name="Course Instructor"),
        ),
        migrations.AlterField(
            model_name="course",
            name="Course_start_date",
            field=models.DateField(verbose_name="Course Start Date"),
        ),
        migrations.AlterField(
            model_name="course",
            name="Course_title",
            field=models.CharField(max_length=200, verbose_name="Course Title"),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(max_length=200, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_content",
            field=models.TextField(verbose_name="Lesson Content"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="education.course",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_name",
            field=models.CharField(max_length=200, verbose_name="Lesson Name"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_order",
            field=models.PositiveIntegerField(verbose_name="Lesson Order"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(max_length=200, verbose_name="Slug"),
        ),
    ]
