# Generated by Django 5.2.3 on 2025-06-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "membership_plan",
                    models.CharField(
                        choices=[
                            ("S", "Standard"),
                            ("P", "Premium"),
                            ("UX", "Ultimate Deluxe"),
                        ],
                        default="S",
                        max_length=2,
                    ),
                ),
                ("membership_active", models.BooleanField(default=True)),
                ("unique_code", models.CharField(max_length=250)),
            ],
        ),
    ]
