# Generated by Django 5.2 on 2025-06-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_membership_options_membership_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["name", "membership_plan"],
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
        migrations.AlterField(
            model_name="membership",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="membership_active",
            field=models.BooleanField(default=True, verbose_name="Membership Active"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="membership_plan",
            field=models.CharField(
                choices=[
                    ("S", "Standard"),
                    ("P", "Premium"),
                    ("UX", "Ultimate Deluxe"),
                ],
                default="S",
                max_length=2,
                verbose_name="Membership Plan",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="unique_code",
            field=models.CharField(max_length=250, verbose_name="Unique Code"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
